spring:
  datasource:
    jdbc-url: jdbc:h2:mem:oauth2
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
  h2:
    console:
      enabled: true

oaut2:
  token:
    access: 120