spring:
  security:
    user:
      name: my.username
      password: 12345
      
  datasource:
    jdbc-url: jdbc:h2:mem:oauth2
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
  h2:
    console:
      enabled: true